package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.Participation;

import java.util.List;

public interface ParticipationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Participation
     *
     * @mbg.generated Sat Apr 18 16:33:13 EEST 2020
     */
    int insert(Participation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Participation
     *
     * @mbg.generated Sat Apr 18 16:33:13 EEST 2020
     */
    List<Participation> selectAll();
}