package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.Venue;

import java.util.List;

public interface VenueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Venue
     *
     * @mbg.generated Sat Apr 18 16:30:40 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Venue
     *
     * @mbg.generated Sat Apr 18 16:30:40 EEST 2020
     */
    int insert(Venue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Venue
     *
     * @mbg.generated Sat Apr 18 16:30:40 EEST 2020
     */
    Venue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Venue
     *
     * @mbg.generated Sat Apr 18 16:30:40 EEST 2020
     */
    List<Venue> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Venue
     *
     * @mbg.generated Sat Apr 18 16:30:40 EEST 2020
     */
    int updateByPrimaryKey(Venue record);
}