package lt.vu.mybatis.model;

import java.util.Date;

public class Club {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Club.id
     *
     * @mbg.generated Sat Apr 18 16:30:40 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Club.name
     *
     * @mbg.generated Sat Apr 18 16:30:40 EEST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Club.start_time
     *
     * @mbg.generated Sat Apr 18 16:30:40 EEST 2020
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Club.end_time
     *
     * @mbg.generated Sat Apr 18 16:30:40 EEST 2020
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Club.venue
     *
     * @mbg.generated Sat Apr 18 16:30:40 EEST 2020
     */
    private Integer venue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Club.id
     *
     * @return the value of dbo.Club.id
     *
     * @mbg.generated Sat Apr 18 16:30:40 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Club.id
     *
     * @param id the value for dbo.Club.id
     *
     * @mbg.generated Sat Apr 18 16:30:40 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Club.name
     *
     * @return the value of dbo.Club.name
     *
     * @mbg.generated Sat Apr 18 16:30:40 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Club.name
     *
     * @param name the value for dbo.Club.name
     *
     * @mbg.generated Sat Apr 18 16:30:40 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Club.start_time
     *
     * @return the value of dbo.Club.start_time
     *
     * @mbg.generated Sat Apr 18 16:30:40 EEST 2020
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Club.start_time
     *
     * @param startTime the value for dbo.Club.start_time
     *
     * @mbg.generated Sat Apr 18 16:30:40 EEST 2020
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Club.end_time
     *
     * @return the value of dbo.Club.end_time
     *
     * @mbg.generated Sat Apr 18 16:30:40 EEST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Club.end_time
     *
     * @param endTime the value for dbo.Club.end_time
     *
     * @mbg.generated Sat Apr 18 16:30:40 EEST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Club.venue
     *
     * @return the value of dbo.Club.venue
     *
     * @mbg.generated Sat Apr 18 16:30:40 EEST 2020
     */
    public Integer getVenue() {
        return venue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Club.venue
     *
     * @param venue the value for dbo.Club.venue
     *
     * @mbg.generated Sat Apr 18 16:30:40 EEST 2020
     */
    public void setVenue(Integer venue) {
        this.venue = venue;
    }
}