package lt.vu.mybatis.model;

public class Participation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Participation.person_id
     *
     * @mbg.generated Sat Apr 18 16:33:13 EEST 2020
     */
    private Integer personId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Participation.club_id
     *
     * @mbg.generated Sat Apr 18 16:33:13 EEST 2020
     */
    private Integer clubId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Participation.person_id
     *
     * @return the value of dbo.Participation.person_id
     *
     * @mbg.generated Sat Apr 18 16:33:13 EEST 2020
     */
    public Integer getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Participation.person_id
     *
     * @param personId the value for dbo.Participation.person_id
     *
     * @mbg.generated Sat Apr 18 16:33:13 EEST 2020
     */
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Participation.club_id
     *
     * @return the value of dbo.Participation.club_id
     *
     * @mbg.generated Sat Apr 18 16:33:13 EEST 2020
     */
    public Integer getClubId() {
        return clubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Participation.club_id
     *
     * @param clubId the value for dbo.Participation.club_id
     *
     * @mbg.generated Sat Apr 18 16:33:13 EEST 2020
     */
    public void setClubId(Integer clubId) {
        this.clubId = clubId;
    }
}