package lt.vu.mybatis.model;

public class Venue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Venue.id
     *
     * @mbg.generated Sat Apr 18 16:30:40 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Venue.venue_address
     *
     * @mbg.generated Sat Apr 18 16:30:40 EEST 2020
     */
    private String venueAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Venue.venue_name
     *
     * @mbg.generated Sat Apr 18 16:30:40 EEST 2020
     */
    private String venueName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Venue.id
     *
     * @return the value of dbo.Venue.id
     *
     * @mbg.generated Sat Apr 18 16:30:40 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Venue.id
     *
     * @param id the value for dbo.Venue.id
     *
     * @mbg.generated Sat Apr 18 16:30:40 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Venue.venue_address
     *
     * @return the value of dbo.Venue.venue_address
     *
     * @mbg.generated Sat Apr 18 16:30:40 EEST 2020
     */
    public String getVenueAddress() {
        return venueAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Venue.venue_address
     *
     * @param venueAddress the value for dbo.Venue.venue_address
     *
     * @mbg.generated Sat Apr 18 16:30:40 EEST 2020
     */
    public void setVenueAddress(String venueAddress) {
        this.venueAddress = venueAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Venue.venue_name
     *
     * @return the value of dbo.Venue.venue_name
     *
     * @mbg.generated Sat Apr 18 16:30:40 EEST 2020
     */
    public String getVenueName() {
        return venueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Venue.venue_name
     *
     * @param venueName the value for dbo.Venue.venue_name
     *
     * @mbg.generated Sat Apr 18 16:30:40 EEST 2020
     */
    public void setVenueName(String venueName) {
        this.venueName = venueName;
    }
}